name: Add preview environment URL to PR

on:
  pull_request:
    types: [labeled]

permissions:
   pull-requests: write

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  comment:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'preview') }}
    runs-on: ubuntu-latest
    steps:
      - name: Comment with preview URL
        uses: thollander/actions-comment-pull-request@v3.0.1
        with:
          message: |
            <div align="center">

            |Preview environmentğŸ‘·ğŸ¼â€â™€ï¸ğŸ—ï¸ |
            |:-:|
            | [PR-${{env.PR_NUMBER}}](https://pr-${{env.PR_NUMBER}}.review.plausible.io)

            </div>
